version: 2.1
jobs:
    build:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout

            - restore_cache:
                  keys:
                      # Find a cache corresponding to this specific requirements.txt checksum
                      # when this file is changed, this key will fail
                      - v1-dependencies-{{ checksum "requirements.txt" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run:
                  name: Install python dependencies
                  command: |
                      make setup
                      source ~/.devops/bin/activate
                      make install
            - save_cache:
                  key: v1-dependencies-{{ checksum "requirements.txt" }}
                  paths:
                      - ~/.devops

            - run:
                  name: Install hadolint
                  command: |
                      sudo make install-hadolint
            - run:
                  name: Run Lint
                  command: |
                      source ~/.devops/bin/activate
                      make lint

workflows:
    main:
        jobs:
            - build
